### PR TITLE
Svelte warning

### PR DESCRIPTION
**Pull request by jorgegorka**

### CODE REVIEW

**Comment by jorgegorka** [comment]
@CHamalainen I've uploaded a new version with your changes and library updates.  Thank you very much for your contribution.

You are now a member of the hall of fame ;-) https://github.com/jorgegorka/svelte-router#contributors

🥇

**Comment by CHamalainen** [comment]
I'm just happy to help! 😄  Thanks again for a great router @jorgegorka

**Comment by CHamalainen** [comment]
> You are now a member of the hall of fame ;-) https://github.com/jorgegorka/svelte-router#contributors

Oops, misspelled my name ;) No biggie, the link still works!

**Comment by jorgegorka** [comment]
@CHamalainen Fixed!

**Pull request merged**
