### PR TITLE
refactor!: refactor the whole code base to esm

### PR DESCRIPTION
**Pull request by si3nloong**
Latest bundling tool such as `snowpack` or `vite` are expecting package in `esm` format. When we are using `cjs` format, likely to hit error when running with those tool. What I amended on the package mainly are :

- refactor to es5 syntax and esm import
- update rollup plugins version
- generate multiple format of bundle file `cjs`, `esm`, `umd`, and update `package.json` to respect each of them
- update `mocha` to use esm instead

### CODE REVIEW

**Comment by si3nloong** [comment]
> Hi!
> Great job you have done here.
> Does this fix the module exporting issue?
> Are the types and functions defined?
> I was planning on working on this but it seems that you have done a good job rewriting it the correct way!

I have yet to work on the typescript type. If there is necessary, will complete it within this week.

**Comment by moalamri** [comment]
Well done :)

**Comment by jorgegorka** [comment]
Hi @si3nloong 

Thank you very much for your PR.  Let me review it this weekend.

Thanks again.

**Comment by moalamri** [comment]
You have done a lot of work :) 
Thank you for sparing your time making this package more awesome

**Comment by jorgegorka** [comment]
Hi @si3nloong  

I've merged your PR in a branch called `version-6`.

**Pull request merged**
